# Generated by Django 4.2.2 on 2023-06-21 12:00

from django.db import migrations


def create_data(apps, schema_editor):
    Manufacturer = apps.get_model('app', 'Manufacturer')
    Contract = apps.get_model('app', 'Contract')
    Product = apps.get_model('app', 'Product')
    CreditApplication = apps.get_model('app', 'CreditApplication')

    manufacturers = [Manufacturer(name=f'Manufacturer {i}') for i in range(1, 10)]
    manufacturers = Manufacturer.objects.bulk_create(manufacturers)

    credit_applications = [CreditApplication() for _ in range(1, 10)]
    credit_applications = CreditApplication.objects.bulk_create(credit_applications)

    contracts = [Contract(credit_application=application) for application in credit_applications]
    contracts = Contract.objects.bulk_create(contracts)

    products = []
    for contract in contracts:
        for manufacturer in manufacturers:
            products.append(
                Product(name=f'Product for contract {contract.id} from {manufacturer.name}',
                        credit_application=contract.credit_application,
                        manufacturer=manufacturer))
    Product.objects.bulk_create(products)


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
